const words = {
    "Animais": [
        "Cachorro-da-terra",
        "Albatroz",
        "Jacaré",
        "Alpaca",
        "Formiga",
        "Tamanduá",
        "Antílope",
        "Macaco",
        "Tatu",
        "Asno",
        "Babuíno",
        "Texugo",
        "Barracuda",
        "Morcego",
        "Urso",
        "Castor",
        "Abelha",
        "Bisão",
        "Javali",
        "Búfalo",
        "Borboleta",
        "Camelo",
        "Capivara",
        "Caribu",
        "Casuar",
        "Gato",
        "Lagarta",
        "Gado",
        "Camurça",
        "Guepardo",
        "Galinha",
        "Chimpanzé",
        "Chinchila",
        "Chasco",
        "Marisco",
        "Cobra",
        "Barata",
        "Bacalhau",
        "Cormorão",
        "Coiote",
        "Caranguejo",
        "Garça",
        "Crocodilo",
        "Corvo",
        "Maçarico",
        "Veado",
        "Dinossauro",
        "Cachorro",
        "Cação",
        "Golfinho",
        "Borrelho",
        "Pombo",
        "Libélula",
        "Pato",
        "Dugongo",
        "Valete-de-tudo",
        "Águia",
        "Equidna",
        "Enguia",
        "Gnu",
        "Elefante-marinho",
        "Veado",
        "Emu",
        "Falcão",
        "Furão",
        "Fringilídeo",
        "Peixe",
        "Flamingo",
        "Mosca",
        "Raposa",
        "Sapo",
        "Gaur",
        "Gazela",
        "Gerbo",
        "Girafa",
        "Mosquito",
        "Gnu",
        "Bode",
        "Pintassilgo",
        "Peixe-dourado",
        "Ganso",
        "Gorila",
        "Gavião",
        "Gafanhoto",
        "Tetraz",
        "Guanaco",
        "Gavião",
        "Hamster",
        "Lebre",
        "Gavião",
        "Ourico",
        "Garça-real",
        "Arenque",
        "Hipopótamo",
        "Vespa",
        "Cavalo",
        "Humano",
        "Beija-flor",
        "Hiena",
        "Ibex",
        "Íbis",
        "Chacal",
        "Jaguar",
        "Gaio",
        "Água-viva",
        "Canguru",
        "Martim-pescador",
        "Coalhada",
        "Kookabura",
        "Kouprey",
        "Cudu",
        "Ave-pia",
        "Alauda",
        "Lêmure",
        "Leopardo",
        "Leão",
        "Lhama",
        "Lagosta",
        "Gafanhoto",
        "Lóris",
        "Piolho",
        "Lírio-do-brejo",
        "Pica-pau",
        "Urso-panda",
        "Pega",
        "Pato-real",
        "Peixe-boi",
        "Mandril",
        "Mantis",
        "Martim-pescador",
        "Suricata",
        "Vison",
        "Toupeira",
        "Mangusto",
        "Macaco",
        "Alce",
        "Mosquito",
        "Rato",
        "Mula",
        "Narval",
        "Salamandra",
        "Salmão",
        "Dólar de areia",
        "Maçarico",
        "Sardinha",
        "Escorpião",
        "Cavalo-marinho",
        "Foca",
        "Tubarão",
        "Ovelha",
        "Musaranho",
        "Gambá",
        "Caracol",
        "Cobra",
        "Pardal",
        "Aranha",
        "Colher-de-pau",
        "Lula",
        "Esquilo",
        "Estorninho",
        "Arraia",
        "Percevejo-fedor",
        "Cegonha",
        "Andorinha",
        "Cisne",
        "Anta",
        "Társio",
        "Cupim",
        "Tigre",
        "Sapo",
        "Truta",
        "Peru",
        "Tartaruga",
        "Víbora",
        "Abutre",
        "Canguru",
        "Morsa",
        "Vespa",
        "Doninha",
        "Baleia",
        "Gato-bravo",
        "Lobo",
        "Carcaju",
        "Wombat",
        "Galinhola",
        "Pica-pau",
        "Minhoca",
        "Tordo",
        "Iaque",
        "Zebra"
    ],
    "Objetos": [
        "Relógio",
        "Caneta",
        "Lápis",
        "Borracha",
        "Caderno",
        "Livro",
        "Cadeira",
        "Mesa",
        "Computador",
        "Celular",
        "Tablet",
        "Televisão",
        "Geladeira",
        "Fogão",
        "Microondas",
        "Liquidificador",
        "Ventilador",
        "Ar-condicionado",
        "Cama",
        "Travesseiro",
        "Cobertor",
        "Edredom",
        "Colchão",
        "Copo",
        "Prato",
        "Talheres",
        "Panela",
        "Frigideira",
        "Chaleira",
        "Cafeteira",
        "Forno",
        "Máquina de lavar",
        "Máquina de secar",
        "Aspirador de pó",
        "Vassoura",
        "Rodo",
        "Balde",
        "Pano",
        "Esponja",
        "Sabão",
        "Detergente",
        "Desinfetante",
        "Água sanitária",
        "Boneca",
        "Carrinho",
        "Bicicleta",
        "Skate",
        "Patins",
        "Bola de futebol",
        "Bola de basquete",
        "Bola de vôlei",
        "Raquete",
        "Bola de tênis",
        "Peteca",
        "Raquete de frescobol",
        "Bola de golfe",
        "Taco de golfe",
        "Rede",
        "Trave",
        "Cesta",
        "Tabela",
        "Rede de vôlei",
        "Rede de basquete",
        "Rede de futebol",
        "Rede de tênis",
        "Rede de frescobol",
        "Rede de golfe",
        "Luva de goleiro",
        "Capacete",
        "Caneleira",
        "Joelheira",
        "Cotoveleira",
        "Tênis",
        "Chinelo",
        "Sapato",
        "Sandália",
        "Bota",
        "Chapéu",
        "Boné",
        "Óculos",
        "Pulseira",
        "Colar",
        "Anel",
        "Brinco",
        "Cinto",
        "Carteira",
        "Bolsa",
        "Mochila",
        "Óculos de sol",
        "Guarda-chuva",
        "Guarda-sol",
        "Chave",
        "Cadeado",
        "Cofre",
        "Porta",
        "Janela",
        "Porta-retrato",
        "Espelho",
        "Tapete",
        "Cortina",
        "Persiana",
        "Luminária",
        "Abajur",
        "Lâmpada",
        "Lustre",
        "Vela",
        "Isqueiro",
        "Fósforo",
        "Vidro",
        "Plástico",
        "Metal",
        "Papel",
        "Madeira",
        "Tecido",
        "Algodão",
        "Lã",
        "Seda",
        "Jeans",
        "Couro"
    ],
    "Comidas": [
    ],
    "Profissões": [],
    "Países": [],
    "Cores": [],
    "Esportes": [],
    "Frutas": [
        "Abacate", "Abacaxi", "Açaí", "Acerola", "Ameixa", "Amora", "Anona", "Arando", "Ata", "Banana",
        "Cacau", "Caju", "Caqui", "Carambola", "Cereja", "Ciriguela", "Coco", "Cranberry", "Damasco", "Durião",
        "Figo", "Framboesa", "Fruta do conde", "Fruta-pão", "Goiaba", "Graviola", "Groselha", "Guaraná", "Jabuticaba", "Jaca",
        "Jambo", "Jamelão", "Jatobá", "Jenipapo", "Kiwi", "Laranja", "Limão", "Maçã", "Mamão", "Manga",
        "Maracujá", "Melancia", "Melão", "Mexerica", "Morango", "Nectarina", "Noni", "Olho-de-dragão", "Papaia", "Pêssego",
        "Pitanga", "Pitaya", "Pêra", "Romã", "Sapoti", "Seriguela", "Tamarindo", "Tangerina", "Tomate", "Umbu",
        "Uva", "Uvaia", "Abiu", "Abricó", "Akee", "Albricoque", "Ameixa-amarela", "Ameixa-de-espanha", "Ameixa-de-são-domingos", "Ameixa-do-pará"
    ]
};

export default words;